"""devpi-smoke: a hello-world package for exercising an internal pip repository."""

from __future__ import annotations

from importlib import metadata
from typing import Any

import six

try:
    from ._build_info import BUILD_ID, BUILT_AT, VERSION
except ImportError:
    # _build_info.py is generated by `pipcheck build` and is not in version control.
    # A fresh checkout, or a build that bypassed the harness, lands here -- and the
    # install checks then fail loudly on the missing stamp, which is what we want.
    VERSION = "0.0.0"
    BUILD_ID = "unstamped"
    BUILT_AT = "1970-01-01T00:00:00Z"

__all__ = ["__version__", "build_info", "hello"]

__version__ = VERSION


def hello(who: str = "world") -> str:
    """Return the canonical greeting."""
    return f"hello, {who}! (devpi-smoke {VERSION} build {BUILD_ID})"


def build_info() -> dict[str, Any]:
    """Describe this build, as stamped in at build time and as the installed metadata.

    Importing six at module scope is deliberate: it is a declared dependency, so a
    missing one should fail loudly at import rather than quietly here.

    `source_version` comes from the stamped module inside the wheel/sdist;
    `dist_version` comes from the installed distribution's metadata. They must agree
    -- a mismatch means the index served an artifact whose filename lies about its
    contents.
    """
    info = {
        "source_version": VERSION,
        "build_id": BUILD_ID,
        "built_at": BUILT_AT,
        "greeting": hello(),
        "six_version": six.__version__,
        "dist_version": None,
        "dist_requires": [],
        "extra_idna": None,
    }

    try:
        info["dist_version"] = metadata.version("devpi-smoke")
        info["dist_requires"] = list(metadata.requires("devpi-smoke") or [])
    except Exception as exc:  # noqa: BLE001 -- report any metadata failure, never raise
        info["dist_version"] = f"<unavailable: {exc}>"

    try:
        # Local on purpose: idna comes from the optional `extra`, so its absence is a
        # legitimate outcome rather than a broken install.
        import idna  # noqa: PLC0415
    except ImportError:
        pass
    else:
        info["extra_idna"] = getattr(idna, "__version__", "present")

    return info
